---
- name: Configure self hosted runner
  hosts:
  - runner
  tasks:
  - name: Include secrets file with offline_token
    include_vars:
      file: "../vars/secrets.yml"

  - name: attach to subscription
    become: true
    shell: |
      subscription-manager register --username={{ rhUser }} --password={{ rhPassword }} --force
      subscription-manager attach
      subscription-manager config --rhsm.manage_repos=1

  - name: Prepare Image Builder server
    become: true
    ansible.builtin.import_role:
      name: infra.osbuild.setup_server

  - name: Install additional packages
    become: true
    ansible.builtin.dnf:
      state: latest
      name: "{{ packages }}"
    vars:
      packages:
      - coreutils
      - glibc-minimal-langpack
      - pykickstart
      - mtools
      - xorriso
      - genisoimage
      - syslinux
      - isomd5sum
      - lorax
      - butane
      - rpmdevtools
      - rpmlint
      - yum-utils
      - createrepo
      - podman

  - name: create actions runner directory
    ansible.builtin.file:
      path: ./actions-runner
      state: directory
      mode: '0755' 
  
  - name: download latest runner package
    get_url: 
      url: https://github.com/actions/runner/releases/download/v2.316.1/actions-runner-linux-x64-2.316.1.tar.gz
      dest: ./actions-runner
      mode: '0644'
  
  - name: extract the installer
    unarchive:
      src: ./actions-runner/actions-runner-linux-x64-2.316.1.tar.gz
      dest: ./actions-runner
      remote_src: yes
