---
- name: build image
  become: true
  hosts: localhost
  tasks:
    - name: Start compose
      infra.osbuild.start_compose:  # noqa only-builtins
        blueprint: "{{ builder_blueprint_name }}"
        compose_type: "{{ _builder_compose_type }}"
        timeout: "{{ builder_request_timeout }}"
      register: builder_compose_start_out

    - name: Wait for compose to finish
      infra.osbuild.wait_compose:  # noqa only-builtins
        compose_id: "{{ builder_compose_start_out['result']['body']['build_id'] }}"
        timeout: "{{ builder_wait_compose_timeout | default(omit) }}"