name: "Compose image"
on:
  workflow_dispatch:
    inputs:
      image-type:
        type: choice
        description: "Image type to generate"
        options:
        - raw
        - vhd
        - gce
        - vmdk
        - openstack
        - oci
        required: true
        default: raw
jobs:
  build:
    name: build rhel9 system based on defined blueprint
    runs-on: "self-hosted"

    steps:
    - uses: actions/checkout@v4
    - name: build image
      shell: bash
      run: |
        composer-cli version
        composer-cli blueprints push ./blueprints/rhel-9-latest-CIS-L1-Server.toml
        composer-cli blueprints list
        compose_id=$(composer-cli --json compose start RHEL-9-latest-CIS-L1-Server ${{ inputs.image-type }} | jq -r ".[].body.build_id")
        while [[ $(composer-cli --json compose info "${compose_id}" | jq -r ".[].body.queue_status") =~ RUNNING|WAITING ]]; do sleep 15; done
        
        # check whether the build succeeded
        [[ $(composer-cli --json compose info "${compose_id}" | jq -r ".[].body.queue_status") =~ FINISHED ]] || exit 1
        
        composer-cli compose image "${compose_id}" --filename rhel-9-latest-CIS-L1-Server.${{ inputs.image-type }}

    - name: upload composed image as workflow artifact
      uses: actions/upload-artifact@v4
      with:
        name: outputimage
        path: "rhel9-base.ami"
