name = "rhel9-base"
description = "RHEL 9 System base image with customizations"
version = "0.0.1"

[[packages]]
name = bash
version = "*"

[[packages]]
name = "git"
version = "*"

[[packages]]
name = "curl"
version = "*"

[[packages]]
name = "wget"
version = "*"

[[packages]]
name = "python3-pip"
version = "*"

[[packages]]
name = "python3-inotify"
version = "*"

[[customizations.user]]
name = "admin"
description = "Admin user"
password = ""
home = "home/admin"
shell = "/usr/bin/bash"
groups = ["users", "wheel"]
